		TITLE	MVLISTNF - Copyright (c) SLR Systems 1994

		INCLUDE	MACROS
		INCLUDE	IO_STRUC

		PUBLIC	MOVE_FILE_LIST_GINDEX_NFN


		.DATA

		EXTERNDEF	_FILE_LIST_GARRAY:STD_PTR_S


		.CODE	ROOT_TEXT

		EXTERNDEF	_move_ecxpath_eax:proc


MOVE_FILE_LIST_GINDEX_NFN	PROC
		;
		;MOVE COMPLETE NFN FROM FILE LIST TO NFN STRUCTURE
		;
		;EAX IS NFN_STRUCT
		;ECX IS FILE_LIST_GINDEX
		;
		MOV	EDX,EAX
		CONVERT	EAX,ECX,_FILE_LIST_GARRAY

		PUSHM	EDI,ESI

		MOV	ECX,[EAX].FILE_LIST_STRUCT.FILE_LIST_NFN.NFN_TOTAL_LENGTH
		MOV	EDI,EDX

		ADD	ECX,NFN_STRUCT.NFN_TEXT+4
		LEA	ESI,FILE_LIST_STRUCT.FILE_LIST_NFN[EAX]

		SHR	ECX,2
		MOV	EAX,[EAX].FILE_LIST_STRUCT.FILE_LIST_PATH_GINDEX

		REP	MOVSD

		TEST	EAX,EAX
		JZ	L1$

		CONVERT	EAX,EAX,_FILE_LIST_GARRAY
		LEA	ECX,FILE_LIST_STRUCT.FILE_LIST_NFN[EAX]

		MOV	EAX,EDX
		push	ECX
		push	EAX
		call	_move_ecxpath_eax
		add	ESP,8
L1$:
		POPM	ESI,EDI

		RET

MOVE_FILE_LIST_GINDEX_NFN	ENDP


		END

