!INCLUDE ..\COMMON\MAKEMACS

FLAGS = $(MASMFLAGS)
SRC = $(BASE)\SUBS



ALL : $(BASE)\LIB\SLRLOAD.LIB $(BASE)\LIBNT\SLRLOAD.LIB $(BASE)\LIBDLL\SLRLOAD.LIB

$(BASE)\LIB\SLRLOAD.LIB : NAPPLOAD.ASM
	call doit.bat

$(BASE)\LIBNT\SLRLOAD.LIB : NAPPLOAD.ASM
	call doit.bat

$(BASE)\LIBDLL\SLRLOAD.LIB : NAPPLOAD.ASM
	call doit.bat

