if not exist ..\LIB mkdir ..\LIB
if not exist ..\LIBNT mkdir ..\LIBNT
if not exist ..\LIBDLL mkdir ..\LIBDLL

OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#-1 /DCOMPRESS_PASS2#0 /DC_LEN#0 /DB_C_LEN#0 /DDEBUG#0 /L/N;
OPTLINK NAPPLOAD/BI/MA;
COMPRESS\OBJ\COMP NAPPLOAD.SYS NAPPLOAD.ZZZ 0X32 0X1F7
BIN2DB NAPPLOAD.ZZZ COMPRESS.DAT 10
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#0 /DCOMPRESS_PASS2#-1 /DDEBUG#0 /DC_LEN#1817 /DB_C_LEN#0B9CH,,napploa1/l/n;
BIN2DB NAPPLOAD.OBJ SLRLOAD.DAT
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#-1 /DCOMPRESS_PASS2#0 /DC_LEN#0 /DB_C_LEN#0 /DDEBUG#-1 ,,NAPPLOA2/L/N;
OPTLINK NAPPLOAD/BI/MA;
COMPRESS\OBJ\COMP NAPPLOAD.SYS NAPPLOAD.ZZZ 0X36 0X228
DIR NAPPLOAD.ZZZ
BIN2DB NAPPLOAD.ZZZ COMPRESS.DAT 10
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#0 /DCOMPRESS_PASS2#-1 /DDEBUG#-1 /DC_LEN#2410 /DB_C_LEN#1132H;
BIN2DB NAPPLOAD.OBJ SLRLOADB.DAT
ML /DHOS=DOSX /c /Cp SLRLOAD.ASM
OPTLIB ..\LIB\SLRLOAD ~+SLRLOAD;
ML /DHOS=W32 /c /Cp SLRLOAD.ASM
OPTLIB ..\LIBNT\SLRLOAD ~+SLRLOAD;
ML /DHOS=W32D /c /Cp SLRLOAD.ASM
OPTLIB ..\LIBDLL\SLRLOAD ~+SLRLOAD;
DEL *.DAT
DEL NAPPLOAD.OBJ
DEL NAPPLOAD.SYS
DEL NAPPLOAD.ZZZ
DEL NAPPLOAD.MAP
DEL SLRLOAD.OBJ

