SET OPTASM=optasm
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#-1 /DCOMPRESS_PASS2#0 /DC_LEN#0 /DB_C_LEN#0 /DDEBUG#0 /L/N;
IF ERRORLEVEL 1 GOTO END
OPTLINK NAPPLOAD/BI/MA;
IF ERRORLEVEL 1 GOTO END
EDIT NAPPLOAD.MAP
EDIT GO.BAT
COMPRESS\OBJ\COMP NAPPLOAD.SYS NAPPLOAD.ZZZ 0X32 0X1F7
IF ERRORLEVEL 1 GOTO END
DIR NAPPLOAD.ZZZ
PAUSE
BIN2DB NAPPLOAD.ZZZ COMPRESS.DAT 10
IF ERRORLEVEL 1 GOTO END
EDIT GO.BAT
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#0 /DCOMPRESS_PASS2#-1 /DDEBUG#0 /DC_LEN#1817 /DB_C_LEN#0B9CH,,napploa1/l/n;
IF ERRORLEVEL 1 GOTO END
BIN2DB NAPPLOAD.OBJ SLRLOAD.DAT
IF ERRORLEVEL 1 GOTO END
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#-1 /DCOMPRESS_PASS2#0 /DC_LEN#0 /DB_C_LEN#0 /DDEBUG#-1 ,,NAPPLOA2/L/N;
IF ERRORLEVEL 1 GOTO END
OPTLINK NAPPLOAD/BI/MA;
IF ERRORLEVEL 1 GOTO END
EDIT NAPPLOAD.MAP
EDIT GO.BAT
COMPRESS\OBJ\COMP NAPPLOAD.SYS NAPPLOAD.ZZZ 0X36 0X228
IF ERRORLEVEL 1 GOTO END
DIR NAPPLOAD.ZZZ
PAUSE
BIN2DB NAPPLOAD.ZZZ COMPRESS.DAT 10
IF ERRORLEVEL 1 GOTO END
EDIT GO.BAT
OPTASM NAPPLOAD /DCOMPRESS_APPLOADER#-1 /DCOMPRESS_PASS1#0 /DCOMPRESS_PASS2#-1 /DDEBUG#-1 /DC_LEN#2410 /DB_C_LEN#1132H;
IF ERRORLEVEL 1 GOTO END
BIN2DB NAPPLOAD.OBJ SLRLOADB.DAT
IF ERRORLEVEL 1 GOTO END
ML /DHOS=DOSX /c /Cp SLRLOAD.ASM
IF ERRORLEVEL 1 GOTO END
OPTLIB \p386\LIB\SLRLOAD ~+SLRLOAD;
IF ERRORLEVEL 1 GOTO END

ML /DHOS=W32 /c /Cp SLRLOAD.ASM
IF ERRORLEVEL 1 GOTO END
OPTLIB \p386\LIBNT\SLRLOAD ~+SLRLOAD;
IF ERRORLEVEL 1 GOTO END

ML /DHOS=W32D /c /Cp SLRLOAD.ASM
IF ERRORLEVEL 1 GOTO END
OPTLIB \p386\LIBDLL\SLRLOAD ~+SLRLOAD;
IF ERRORLEVEL 1 GOTO END

DEL *.DAT
DEL NAPPLOAD.OBJ
DEL NAPPLOAD.SYS
DEL NAPPLOAD.ZZZ
DEL NAPPLOAD.MAP
IF ERRORLEVEL 1 GOTO END
DEL SLRLOAD.OBJ

:END

