		INCLUDE MACROS

		PUBLIC	TEMP_RECORD

		.DATA?

TEMP_RECORD	DB	TEMP_RECORD_SIZE+16 DUP(?)


		PUBLIC	SLR_PREV_SEG,SLRBUF_PTR,NEXT_AVAIL,NEXT_AVAIL_2,COMPRESS_TABLE,COMPRESS_TABLE_LENGTH,PUTSTUFF_SMALL
		PUBLIC	PUTSTUFF,SLR_FLUSHSTUFF,FIX_BUFFERS,SLR_NEXT_SEG,OLD_MATCHED_COUNT,OLD_OFFSET,INPTR,INCNT,INFILE_BYTES_LEFT
		PUBLIC	SLR_CPOS,SLR_VARS,SLR_DATA,SLR_INBUF_LIMIT,SLR_WORD,NEW_REPT_ADDR,DONT_PACK,SEED_SIZE,ASCIZ0_HANDLE,ASCIZ0
		PUBLIC	SLR_SCAN_LIMIT,DEL_INST_COUNT,SLR_DICT_COUNT,SLR_DICT2_COUNT,PUTBYTE_ADDR1,PUTBYTE_ADDR2,PUTBYTE_TEMP
		PUBLIC	SLR_MASK,SLR_BYTES_LEFT,SLR_TMP_PTR,SLR_INPUT_PTR,HUF_PUT_PTR,ASCIZ1,ASCIZ1_HANDLE,PACK_BYTES_LEFT
		PUBLIC	OUTBUF_BYTES_LEFT,OUTBUF_SIZE,OUTBUF_PTR,PACK_BYTES_PTR

INPTR			DW	?
INCNT			DW	?
INFILE_BYTES_LEFT	DD	?
NEW_REPT_ADDR		DD	?
DONT_PACK		DW	?
SEED_SIZE		DW	?
ASCIZ0_HANDLE		DW	?
ASCIZ0			DB	64 DUP(?)
ASCIZ1_HANDLE		DW	?
ASCIZ1			DB	64 DUP(?)
PACK_BYTES_LEFT		DW	?
OUTBUF_BYTES_LEFT	DW	?
OUTBUF_SIZE		DW	?
OUTBUF_PTR		DD	?
PACK_BYTES_PTR		DD	?

SLR_PREV_SEG		DW	?
SLR_NEXT_SEG		DW	?
OLD_MATCHED_COUNT	DW	?
OLD_OFFSET		DW	?
SLRBUF_PTR		DD	?
SLR_BYTES_LEFT		DD	?
SLR_TMP_PTR		DD	?
SLR_INPUT_PTR		DD	?
HUF_PUT_PTR		DD	?
NEXT_AVAIL		DW	?
NEXT_AVAIL_2		DW	?
SLR_CPOS		DW	?
SLR_VARS		DW	?
SLR_DATA		DW	?
SLR_INBUF_LIMIT		DW	?
SLR_WORD		DW	?
SLR_MASK		DW	?
SLR_SCAN_LIMIT		DW	?
DEL_INST_COUNT		DW	?
SLR_DICT_COUNT		DW	?
SLR_DICT2_COUNT		DW	?
PUTBYTE_ADDR1		DW	?
PUTBYTE_ADDR2		DW	?
PUTBYTE_TEMP		DW	?

COMPRESS_TABLE		LABEL	WORD
PUTSTUFF_SMALL		DW	?
PUTSTUFF		DW	?
SLR_FLUSHSTUFF		DW	?
FIX_BUFFERS		DW	?
COMPRESS_TABLE_LENGTH	EQU	$-COMPRESS_TABLE

DOFLAG		MACRO	FLAG
		PUBLIC	FLAG
FLAG		DB	?
NUM_FLAGS	=	NUM_FLAGS+1
		ENDM

NUM_FLAGS	=	0

DOFLAG	DICT_FULL
DOFLAG	DICT2_FULL
DOFLAG	OUTBUF_EXISTS
DOFLAG	NO_SLRPACKING_DONE
DOFLAG	COMP_FIRST_INPUT



		END

