		TITLE OPTLNK - Copyright (c) SLR Systems 1994

		INCLUDE MACROS
		INCLUDE	INITCODE
		INCLUDE	IO_STRUC
		INCLUDE	WIN32DEF
		INCLUDE	WINMACS

		PUBLIC	OPTLINK,_optlink_restart,main

		.DATA

		EXTERNDEF	MYSTACK:DWORD,ALLOCATED_BLOCKS:DWORD,__psp:DWORD,_ERR_COUNT:DWORD,_OUTFILE_GINDEX:DWORD
		EXTERNDEF	ALLOCS_TABLES:DWORD,CVPACK_PID:DWORD,_EXE_DEVICE:DWORD,MAP_DEVICE:DWORD,MAPFILE_GINDEX:DWORD
		EXTERNDEF	NUMBLKS:DWORD,STARTING_ESP:DWORD,PMODE:DWORD,ALLOCATED_IO_BLOCKS:DWORD,TYPE_COLLISION_MAX:DWORD
		EXTERNDEF	OBJ_DEVICE:DWORD,IND_DEVICE:DWORD,PARALLEL_TABLES:DWORD,WORKFILE:DWORD,CVPACK_ADDR:DWORD
		EXTERNDEF	OLD_DTA:DWORD,MAP_THREAD_HANDLE:DWORD,HOST_ESP:DWORD

		EXTERNDEF	MYO_STUFF:MYO_STRUCT,_FILE_LIST_GARRAY:STD_PTR_S,OUTFILE_GARRAY:STD_PTR_S
		EXTERNDEF	LOCKED_STUFF:LKD_ALLOC_STRUCT,MYI_STUFF:MYI_STRUCT,MAP_THREAD_TERM_SEM:QWORD


		.CODE	ROOT_TEXT

		EXTERNDEF	_optlink:proc
		EXTERNDEF	_capture_eax:proc
		EXTERNDEF	LNKINIT:PROC,PASS1_STUFF:PROC,WRITE_MAP:PROC,MIDDLE_STUFF:PROC,PASS2_STUFF:PROC,EXIT:PROC
		EXTERNDEF	_close_handle:proc,CBTA16:PROC,DO_DOSSEMWAIT_SSAX:PROC,CBTA32:PROC
		EXTERNDEF	LOUTALL_CON:PROC,CAPTURE_EAX:PROC,DOT:PROC,ERR_RET:PROC,SAY_VERBOSE:PROC
		EXTERNDEF	_abort:proc,CVPACK_RUNNER:PROC,_release_minidata:proc,FLUSH_PHYS_TABLE:PROC,_flush_trunc_close:proc
		EXTERNDEF	RELEASE_ESBX:PROC,HEXWOUT:PROC,RELEASE_BLOCK:PROC,SAY_CVPACK:PROC,_err_abort:proc,XCNOTIFY:PROC
		EXTERNDEF	CLOSE_LIB_FILES:PROC,END_OF_INDIRECT:PROC,RELEASE_PARALLEL_ARRAY:PROC,FLUSH_PHYS_IO_TEMP:PROC

		EXTERNDEF	ALLOCS_TABLES_LEN:ABS,DGROUP_STEPPED_ERR:ABS,FATAL_RESTART_ERR:ABS,PARALLEL_TABLES_LEN:ABS


_optlink_restart	PROC
		MOV	AL,FATAL_RESTART_ERR
		push	EAX
		call	_err_abort
_optlink_restart	ENDP


main		PROC
		INITCODE0
		call	_optlink
main		ENDP


OPTLINK		EQU	main


		END	OPTLINK

