		TITLE FINSEGAT - Copyright (c) 1994 by SLR Systems

		INCLUDE MACROS
		INCLUDE	SEGMENTS

		PUBLIC	FIND_SEGAT_LOCATION


		.DATA

		EXTERNDEF	FIRST_FINAL_SEGMENT_GINDEX:DWORD,SEG_FRAME:DWORD

		EXTERNDEF	SEGMENT_GARRAY:STD_PTR_S


		.CODE	PASS1_TEXT


FIND_SEGAT_LOCATION	PROC
		;
		;WE SCAN LIST OF ABSOLUTE SEGMENTS FOR PLACE TO PUT THIS ONE (IN NUMERICAL ORDER FOR ROM-LINK)
		;
		;RETURN EAX POINTING TO PLACE TO RECEIVE NEW SEGMENT...
		;
		;SET CARRY IF THERE IS AN OVERLAP...
		;
		MOV	EAX,OFF FIRST_FINAL_SEGMENT_GINDEX-SEGMENT_STRUCT._SEG_NEXT_SEG_GINDEX

		MOV	ECX,SEG_FRAME
L2$:
		ASSUME	EAX:PTR SEGMENT_STRUCT
		MOV	EDX,EAX
		MOV	EAX,[EAX]._SEG_NEXT_SEG_GINDEX

		TEST	EAX,EAX
		JZ	L9$

		CONVERT	EAX,EAX,SEGMENT_GARRAY

		CMP	ECX,[EAX]._SEG_OFFSET
		JAE	L2$
L9$:
		MOV	EAX,EDX

		RET

FIND_SEGAT_LOCATION	ENDP

		END

