		TITLE	INST_INIT - Copyright (C) 1994 SLR Systems

		INCLUDE	MACROS

		PUBLIC	COMMON_INST_INIT


		.CODE	ROOT_TEXT

		EXTERNDEF	GET_NEW_LOG_BLK:PROC


COMMON_INST_INIT	PROC
		;
		;EAX POINTS TO _STUFF ALLOCS STRUCTURE THAT IS TO BE INITIALIZED WITH A HASH TABLE
		;
		;MODIFIES AX,BX,CX,DI,ES
		;
		PUSHM	EDI,ECX,EBX
		MOV	EBX,EAX
		ASSUME	EBX:PTR ALLOCS_STRUCT

		CALL	GET_NEW_LOG_BLK

		MOV	EDI,EAX
		MOV	[EBX].ALLO_HASH_TABLE_PTR,EAX
		MOV	EAX,PRIME_2K
		MOV	[EBX].ALLO_BLK_LIST,EDI	;FIRST BLOCK
		MOV	[EBX].ALLO_HASH,EAX
		LEA	EAX,[EDI+2K*4]
		MOV	ECX,PAGE_SIZE-2K*4
		MOV	[EBX].ALLO_PTR,EAX
		LEA	EAX,[EBX].ALLO_BLK_LIST+4
		MOV	[EBX].ALLO_CNT,ECX
		MOV	[EBX].ALLO_NEXT_BLK,EAX

		MOV	[EBX].ALLO_BLK_CNT,1

		MOV	ECX,2K
		XOR	EAX,EAX
		REP	STOSD
		POPM	EBX,ECX,EDI
		RET

COMMON_INST_INIT	ENDP

		END

